// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DxSection: typeof import('./components/sections/DxSection.vue')['default']
    Feature: typeof import('./components/feature/Feature.vue')['default']
    HeroSection: typeof import('./components/sections/HeroSection.vue')['default']
    MdiGithub: typeof import('~icons/mdi/github')['default']
    MdiMinus: typeof import('~icons/mdi/minus')['default']
    MdiPlus: typeof import('~icons/mdi/plus')['default']
    MdiRestore: typeof import('~icons/mdi/restore')['default']
    MdiThemeLightDark: typeof import('~icons/mdi/theme-light-dark')['default']
    MyButton: typeof import('./components/shared/MyButton.vue')['default']
    MySection: typeof import('./components/shared/MySection.vue')['default']
    PiniaSection: typeof import('./components/sections/PiniaSection.vue')['default']
  }
}

export { }
